version: 2

jobs:
  build:
    docker:
      - image: registry.gitlab.com/glarch/container:makeiso
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: "Run ESLint"
          command: |
            uname -a
            lsmod
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
