version: 2

machine:
  node:
    version: 9.6.1

dependencies:
  override:
    - npm install --dev

jobs:
  test:
    pre:
      - mkdir -p $CIRCLE_TEST_REPORTS/reports
      - eslint ./src/ --format junit --output-file $CIRCLE_TEST_REPORTS/reports/eslint.xml
