version: 2

machine:
  node:
    version: 9.6.1

dependencies:
  override:
    - npm install --dev

jobs:
  test:
    - run:
      - mkdir -p $CIRCLE_TEST_REPORTS/reports
      - eslint ./src/ --format junit --output-file $CIRCLE_TEST_REPORTS/reports/eslint.xml

workflows:
  version: 2
  test:
    jobs:
      - test
