version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run: npm install eslint --save-dev
      - run: ./node_modules/.bin/eslint --init
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: "Run ESLint"
          command: ./node_modules/.bin/eslint ./src/ --format junit -o reports/junit/eslint.xml
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
