version: 2

jobs:
  build:
    docker:
      # 最新のLTS版を使用
      - image: circleci/node:8.9.4-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: "Run ESLint"
          command: npm test
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
